name: console_chat_app
description: A console-based chat application in Dart.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5
  web_socket_channel: ^2.3.0
  equatable: ^2.0.5
  bloc: ^8.1.0
